-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2021-03-02 02:32:27 CST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE building (
    building_id  NUMBER(7) NOT NULL,
    name         VARCHAR2(50),
    address      VARCHAR2(40),
    city         VARCHAR2(25),
    state        CHAR(2),
    zip          VARCHAR2(5)
);

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( building_id );

CREATE TABLE reservation (
    reservation_id                  NUMBER(7),
    studyroom_room_id               NUMBER(7) NOT NULL,
    studyroom_building_building_id  NUMBER(7) NOT NULL,
    time_in                         TIMESTAMP,
    time_out                        TIMESTAMP,
    cancellation_status             NUMBER,
    cancellation_reason             VARCHAR2(50)
);

CREATE UNIQUE INDEX reservation__idx ON
    reservation (
        studyroom_building_building_id
    ASC,
        studyroom_room_id
    ASC );

CREATE TABLE studyroom (
    room_id               NUMBER(7) NOT NULL,
    name                  VARCHAR2(50),
    type                  VARCHAR2(50),
    description           VARCHAR2(50),
    status                NUMBER,
    building_building_id  NUMBER(7) NOT NULL
);

ALTER TABLE studyroom ADD CONSTRAINT studyroom_pk PRIMARY KEY ( building_building_id,
                                                                room_id );

CREATE TABLE "user" (
    cwid        NUMBER(7),
    first_name  VARCHAR2(50),
    last_name   VARCHAR2(50),
    email       VARCHAR2(50)
);

ALTER TABLE reservation
    ADD CONSTRAINT reservation_studyroom_fk FOREIGN KEY ( studyroom_building_building_id,
                                                          studyroom_room_id )
        REFERENCES studyroom ( building_building_id,
                               room_id );

-- Error - Foreign Key reservation_user_FK has no columns

ALTER TABLE studyroom
    ADD CONSTRAINT studyroom_building_fk FOREIGN KEY ( building_building_id )
        REFERENCES building ( building_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             1
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0